create table if not exists public.gas_entries (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  time time not null default current_time,
  operator text not null,
  "gasType" text not null,
  location text not null,
  opening numeric not null default 0,
  received numeric not null default 0,
  used numeric not null default 0,
  closing numeric generated always as (opening + received - used) stored,
  unit text not null default 'm³',
  status text not null default 'Normal' check (status in ('Normal','Low','Critical')),
  notes text not null default ''
);
alter table public.gas_entries enable row level security;
create policy "workspace can view gas entries" on public.gas_entries for select to anon, authenticated using (true);
create policy "workspace can add gas entries" on public.gas_entries for insert to anon, authenticated with check (true);
