import {useEffect,useMemo,useState} from 'react';
import {Activity, Bell, BookOpen, CalendarDays, ChevronDown, CircleGauge, Download, Droplets, Factory, LayoutDashboard, Menu, PackageOpen, Plus, Search, Settings, TrendingDown, Users, X} from 'lucide-react';
import {entries as seed, type GasEntry} from './data'; import {supabase} from './supabase';

const gases=['All gases','Argon','Oxygen','Acetylene','CO₂','Nitrogen','Propane'];
const gasClass=(g:string)=>`gas ${g.toLowerCase().replace('₂','2')}`;
export default function App(){
 const [rows,setRows]=useState<GasEntry[]>(seed),[query,setQuery]=useState(''),[gas,setGas]=useState('All gases'),[open,setOpen]=useState(false),[nav,setNav]=useState(false),[sync,setSync]=useState(false);
 useEffect(()=>{if(!supabase)return; supabase.from('gas_entries').select('*').order('date',{ascending:false}).then(({data})=>{if(data?.length){setRows(data as GasEntry[]);setSync(true)}})},[]);
 const filtered=useMemo(()=>rows.filter(r=>(gas==='All gases'||r.gasType===gas)&&`${r.operator} ${r.location} ${r.notes}`.toLowerCase().includes(query.toLowerCase())),[rows,gas,query]);
 const usage=rows.reduce((n,r)=>n+r.used,0), stock=rows.reduce((n,r)=>n+r.closing,0), alerts=rows.filter(r=>r.status!=='Normal').length;
 const exportCsv=()=>{const keys=Object.keys(rows[0]) as (keyof GasEntry)[]; const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]).replaceAll('"','""')}"`).join(','))].join('\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='gas-control.csv';a.click()};
 return <div className="app">
  <aside className={nav?'show':''}><div className="brand"><div className="brandmark"><Droplets/></div><div>GAS<span>CONTROL</span></div><button className="navclose" onClick={()=>setNav(false)}><X/></button></div><div className="site"><Factory/><div><small>FACILITY</small><b>Fabrication Workshop</b></div><ChevronDown/></div>
   <nav><small>WORKSPACE</small><a className="active"><LayoutDashboard/>Overview</a><a><BookOpen/>Gas log</a><a><PackageOpen/>Inventory <em>2</em></a><a><Activity/>Usage analytics</a><small>MANAGEMENT</small><a><Users/>Team</a><a><Settings/>Settings</a></nav>
   <div className="operator"><div className="avatar">MC</div><div><b>Marcus Chen</b><small>Workshop manager</small></div><ChevronDown/></div>
  </aside>
  <main><header><button className="menub" onClick={()=>setNav(true)}><Menu/></button><div className="crumb">WORKSHOP <span>/</span> GAS CONTROL</div><div className="headright"><div className={`sync ${sync?'live':''}`}><i/> {sync?'Supabase connected':'Demo workspace'}</div><button className="iconbtn"><Bell/><i/></button><button className="export" onClick={exportCsv}><Download/> Export</button></div></header>
   <div className="content"><section className="welcome"><div><p className="eyebrow">WEDNESDAY · 09 SEPTEMBER</p><h1>Good afternoon, Marcus.</h1><p>Here’s what’s happening with your workshop gas supply.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus/> Log gas movement</button></section>
   <section className="stats"><Stat icon={<CircleGauge/>} label="TOTAL STOCK" value={stock.toLocaleString()} unit="units" sub="Across 6 gas types" tone="blue"/><Stat icon={<TrendingDown/>} label="USED THIS WEEK" value={usage.toLocaleString()} unit="units" sub="↓ 8.4% from last week" tone="green"/><Stat icon={<CalendarDays/>} label="TODAY'S ENTRIES" value="4" unit="logs" sub="Last entry at 14:30" tone="violet"/><Stat icon={<Bell/>} label="STOCK ALERTS" value={String(alerts)} unit="items" sub="Require attention" tone="orange"/></section>
   <section className="panel"><div className="panelhead"><div><h2>Recent movements</h2><p>Gas usage and stock changes across the workshop.</p></div><div className="filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records..."/></label><select value={gas} onChange={e=>setGas(e.target.value)}>{gases.map(g=><option key={g}>{g}</option>)}</select></div></div>
    <div className="tablewrap"><table><thead><tr><th>DATE & TIME</th><th>GAS TYPE</th><th>LOCATION</th><th>OPENING</th><th>RECEIVED</th><th>USED</th><th>CLOSING</th><th>STATUS</th><th>OPERATOR</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{new Date(r.date+'T00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</b><small>{r.time}</small></td><td><span className={gasClass(r.gasType)}>{r.gasType.slice(0,2).toUpperCase()}</span><b>{r.gasType}</b></td><td>{r.location}</td><td>{r.opening} <small>{r.unit}</small></td><td className="received">{r.received?`+${r.received}`:'—'}</td><td className="used">−{r.used}</td><td><b>{r.closing}</b> <small>{r.unit}</small></td><td><span className={`status ${r.status.toLowerCase()}`}><i/>{r.status}</span></td><td><div className="person">{r.operator.split(' ').map(n=>n[0]).join('')}<span>{r.operator}</span></div></td></tr>)}</tbody></table></div><div className="foot">Showing {filtered.length} of {rows.length} entries <button>View full gas log →</button></div>
   </section><p className="hint">Data is shown in demo mode until Supabase environment variables are configured.</p></div>
  </main>{open&&<EntryModal close={()=>setOpen(false)} add={async(r)=>{const entry={...r,id:Date.now()};setRows(x=>[entry,...x]);setOpen(false);if(supabase){const {id:_,closing:__,...record}=r;void _;void __;await supabase.from('gas_entries').insert(record)}}}/>
 </div>
}
function Stat({icon,label,value,unit,sub,tone}:{icon:React.ReactNode,label:string,value:string,unit:string,sub:string,tone:string}){return <article className="stat"><div className={`statIcon ${tone}`}>{icon}</div><div><small>{label}</small><strong>{value} <span>{unit}</span></strong><p>{sub}</p></div></article>}
function EntryModal({close,add}:{close:()=>void,add:(r:GasEntry)=>void}){const [type,setType]=useState('Argon'),[used,setUsed]=useState(0),[opening,setOpening]=useState(0);return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={e=>{e.preventDefault();add({id:0,date:new Date().toISOString().slice(0,10),time:new Date().toTimeString().slice(0,5),operator:'Marcus Chen',gasType:type,location:'Bay 01',opening,received:0,used,closing:opening-used,unit:'m³',status:opening-used<50?'Low':'Normal',notes:''})}}><button type="button" className="close" onClick={close}><X/></button><p className="eyebrow">NEW ENTRY</p><h2>Log gas movement</h2><p>Record usage or stock received at the workshop.</p><div className="formgrid"><label>Gas type<select value={type} onChange={e=>setType(e.target.value)}>{gases.slice(1).map(g=><option key={g}>{g}</option>)}</select></label><label>Location<select><option>Bay 01</option><option>Bay 02</option><option>Store</option><option>Yard</option></select></label><label>Opening stock<input required type="number" onChange={e=>setOpening(+e.target.value)}/></label><label>Amount used<input required type="number" onChange={e=>setUsed(+e.target.value)}/></label></div><div className="balance"><span>Calculated closing stock</span><b>{opening-used} m³</b></div><div className="actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Save movement</button></div></form></div>}
